### ISSUE TITLE
Integration with Dash

### ISSUE THREAD

**Issue by Kapeli** [financeCoding/dart-carte-du-jour#97]
I'm the developer behind [Dash](http://kapeli.com/dash), an API documentation browser for OS X.

I'd like to allow Dash users to grab docs for Dart packages directly from within the app.

What I need:
- [ ] A search API for the packages that have docs on dartdocs.org. Something simple like a substring match over the package names is fine
- [ ] Once I have a package name, I need a way to get all the available versions that package has
- [ ] Once I have a package name and a version, a way to download the docs for that version (the HTML files).

Are any of these on the roadmap or are there ways to get to them right now? Thank you!

**Comment by astashov** [comment]
Hi!

> A search API for the packages that have docs on dartdocs.org. Something simple like a substring match over the package names is fine

What format of response do you need the search API to be? Like dartdocs.org/search?query=doc, and it will return e.g. the JSON list of the matching package names (like 'dartdoc', etc)?

> Once I have a package name, I need a way to get all the available versions that package has

Again, what format of the request/response? Something like dartdocs.org/documentation/dartdoc/index.json would return the links to all the versions of the dartdoc package, would that work?

> Once I have a package name and a version, a way to download the docs for that version (the HTML files).

Would something like dartdocs.org/documentation/dartdoc/0.7.0/index.json returning the list of all the HTML files with the documentation work?

**Comment by Kapeli** [comment]
> What format of response do you need the search API to be? Like dartdocs.org/search?query=doc, and it will return e.g. the JSON list of the matching package names (like 'dartdoc', etc)?

> Again, what format of the request/response? Something like dartdocs.org/documentation/dartdoc/index.json would return the links to all the versions of the dartdoc package, would that work?

Sounds good. JSON is fine.

> Would something like dartdocs.org/documentation/dartdoc/0.7.0/index.json returning the list of all the HTML files with the documentation work?

Not really. I need to download all the HTML files when I generate the docset, so it would take a very long time for larger packages. Can you provide a tgz/zip archive with all the files? This might be a nice feature to have in dartdocs.org as a whole, as it would allow all users to download the docs they want for offline use.

**Comment by astashov** [comment]
> Can you provide a tgz/zip archive with all the files?

You mean the archive with all the files per package? I.e. something like dartdocs.org/documentation/dartdoc/0.7.0/package.tar.gz?

**Comment by Kapeli** [comment]
Yep.

**Comment by astashov** [comment]
I'm currently working on the next version of dartdocs.org. I'm going to add the packaging (package.tar.gz) and list of versions feature (dartdocs.org/documentation/dartdoc/index.json) to it, but probably will not add the search API right away, since it seems to require a web server, and currently the dartdocs.org generator is planned to be purely static.

But I can give you e.g. the list of all the packages, which have the docs generated, in one big JSON file, would that work instead of the search API?

**Comment by Kapeli** [comment]
> But I can give you e.g. the list of all the packages, which have the docs generated, in one big JSON file, would that work instead of the search API?

That's ok with me, but please note that I'd load that list every time a new user searches for a package (I'll cache it for a while for subsequent searches though), so it might increase server load and/or bandwidth usage.

**Comment by astashov** [comment]
That should be fine, it will be stored on Google Cloud Storage, cached via CloudFlare CDN, and also gzipped (hopefully, your client supports accepting a response with `Content-Encoding: gzip`. Does it?)

**Comment by Kapeli** [comment]
Yep, gzip is supported.

**Comment by astashov** [comment]
Ok, cool. I'll let you know in this thread when it's gonna be ready. Probably at the beginning of November.

**Comment by Kapeli** [comment]
Great. Thank you!

**Comment by astashov** [comment]
No problem. I'm a fan of your product, and also would like to have Dart package docs installed and accessible offline on my computer :)

**Comment by sethladd** [comment]
Handling over at https://github.com/astashov/dartdoc-generator
